rpc:
  token: ypjdYOzNd4FwENJiEARMLWwK0v7QUHPW
governance:
  timeoutMillSeconds: 0
registrycenter:
  connectionStrings: silky.zoo1:2181,silky.zoo2:2181,silky.zoo3:2181;silky.zoo4:2181,silky.zoo5:2181,silky.zoo6:2181
  type: Zookeeper
distributedCache:
  redis:
    isEnabled: true
    configuration: silky.redis:6379,defaultDatabase=0
gateway:
  jwtSecret: UnMTH4QvAAp0BLYyEmdXYjoAOv4biHW4
swaggerDocument:
  organizationMode: Group
  termsOfService: https://www.github.com/liuhll/silky
healthChecksUI:
  healthChecks:
    - name: silkyrpc
      uri: http://silky.sample.gateway/silkyrpc/healthz
  evaluationTimeinSeconds: 30
  minimumSecondsBetweenFailureNotifications: 60
dashboard:
  displayWebApiInSwagger: false
  useAuth: false
  wrapperResponse: true
  dashboardLoginApi: /api/account/dashboard/login
  externalLinks:
    - title: "message.swagger"
      path: "http://localhost"
      icon: "iconfont icon-swagger"
    - title: "SkyWalking"
      path: "http://localhost:8180"
    - title: "Github"
      path: "https://github.com/liuhll/silky"
      icon: "iconfont icon-github"
    - title: "Gitee"
      path: "https://gitee.com/liuhll2/silky"
      icon: "iconfont icon-gitee2"
skyWalking:
  transport:
    gRPC:
      servers: "oap:11800"