rpc:
  token: rpcTokenValue
governance:
  timeoutMillSeconds: 0
registrycenter:
  connectionStrings: silky.zoo1:2181,silky.zoo2:2181,silky.zoo3:2181;silky.zoo4:2181,silky.zoo5:2181,silky.zoo6:2181
  type: registrycentertype
distributedCache:
  redis:
    isEnabled: true
    configuration: silky.redis:6379,defaultDatabase=0
connectionStrings:
  default: server=silky.mysql;port=3306;database=SilkyApp;uid=root;pwd=qwe!P4ss;
skyWalking:
  transport:  
    gRPC:
      servers: "oap:11800"