version: '3.7'

services:
  Silky.AccountHost:
    image: silkyframework/sample.account:${TAG:-latest}
    build:
      context: ..
      dockerfile: microservices/account/Silky.AccountHost/Dockerfile
    volumes:
      - ./logs/account:/app/logs    
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT:-Development}
      rpc__token: ${rpc__token:-ypjdYOzNd4FwENJiEARMLWwK0v7QUHPW}
      governance__timeoutMillSeconds: ${governance__timeoutMillSeconds:-5000}
      registrycenter__type: ${registrycenter_type:-Zookeeper}
      registrycenter__connectionStrings: ${registrycenter_connectionStrings:-silky.zoo1:2181,silky.zoo2:2181,silky.zoo3:2181;silky.zoo4:2181,silky.zoo5:2181,silky.zoo6:2181}
      distributedCache__redis__isEnabled: ${distributedCache__redis__isEnabled:-true}
      distributedCache__redis__configuration: ${distributedCache__redis__configuration:-silky.redis:6379,defaultDatabase=0}
      connectionStrings__default:  ${connectionStrings__account:-server=silky.mysql;port=3306;database=account;uid=root;pwd=qwe!P4ss;}
      jwtSettings__secret:  ${jwtSettings__secret:-UnMTH4QvAAp0BLYyEmdXYjoAOv4biHW4}
      skyWalking__transport__gRPC__servers: ${skyWalking__transport__gRPC__servers:-oap:11800}
    networks: 
      - silky_service_net
    
  Silky.OrderHost:
    image: silkyframework/sample.order:${TAG:-latest}
    build:
      context: ..
      dockerfile: microservices/order/Silky.OrderHost/Dockerfile
    volumes:
      - ./logs/order:/app/logs
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT:-Development}
      rpc__token: ${rpc__token:-ypjdYOzNd4FwENJiEARMLWwK0v7QUHPW}
      governance__timeoutMillSeconds: ${governance__timeoutMillSeconds:-5000}
      registrycenter__type: ${registrycenter_type:-Zookeeper}
      registrycenter__connectionStrings: ${registrycenter_connectionStrings:-silky.zoo1:2181,silky.zoo2:2181,silky.zoo3:2181;silky.zoo4:2181,silky.zoo5:2181,silky.zoo6:2181}
      distributedCache__redis__isEnabled: ${distributedCache__redis__isEnabled:-true}
      distributedCache__redis__configuration: ${distributedCache__redis__configuration:-silky.redis:6379,defaultDatabase=0}
      connectionStrings__default:  ${connectionStrings__order:-server=silky.mysql;port=3306;database=order;uid=root;pwd=qwe!P4ss;}
      skyWalking__transport__gRPC__servers: ${skyWalking__transport__gRPC__servers:-oap:11800}
    networks: 
      - silky_service_net
  
  Silky.StockHost:
    image: silkyframework/sample.stock:${TAG:-latest}
    build:
      context: ..
      dockerfile: microservices/stock/Silky.StockHost/Dockerfile
    volumes:
      - ./logs/stock:/app/logs
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT:-Development}
      rpc__token: ${rpc__token:-ypjdYOzNd4FwENJiEARMLWwK0v7QUHPW}
      governance__timeoutMillSeconds: ${governance__timeoutMillSeconds:-5000}
      registrycenter__type: ${registrycenter_type:-Zookeeper}
      registrycenter__connectionStrings: ${registrycenter_connectionStrings:-silky.zoo1:2181,silky.zoo2:2181,silky.zoo3:2181;silky.zoo4:2181,silky.zoo5:2181,silky.zoo6:2181}
      distributedCache__redis__isEnabled: ${distributedCache__redis__isEnabled:-true}
      distributedCache__redis__configuration: ${distributedCache__redis__configuration:-silky.redis:6379,defaultDatabase=0}
      connectionStrings__default:  ${connectionStrings__stock:-server=silky.mysql;port=3306;database=stock;uid=root;pwd=qwe!P4ss;}
      skyWalking__transport__gRPC__servers: ${skyWalking__transport__gRPC__servers:-oap:11800}
    networks: 
      - silky_service_net

  Silky.GatewayHost:
    image: silkyframework/sample.gateway:${TAG:-latest}
    build:
      context: ..
      dockerfile: microservices/gateway/Silky.GatewayHost/Dockerfile
    volumes:
      - ./logs/gateway:/app/logs      
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT:-Development}
      ASPNETCORE_ENVIRONMENT: ${DOTNET_ENVIRONMENT:-Development}
      rpc__token: ${rpc__token:-ypjdYOzNd4FwENJiEARMLWwK0v7QUHPW}
      registrycenter__type: ${registrycenter__type:-Zookeeper}
      registrycenter__connectionStrings: ${registrycenter__connectionStrings:-silky.zoo1:2181,silky.zoo2:2181,silky.zoo3:2181;silky.zoo4:2181,silky.zoo5:2181,silky.zoo6:2181}
      distributedCache__redis__isEnabled: ${distributedCache__redis__isEnabled:-true}
      distributedCache__redis__configuration: ${distributedCache__redis__configuration:-silky.redis,defaultDatabase=0}
      skyWalking__transport__gRPC__servers: ${skyWalking__transport__gRPC__servers:-oap:11800}
      gateway__jwtSecret: ${gateway__jwtSecret:-UnMTH4QvAAp0BLYyEmdXYjoAOv4biHW4}
      dashboard__displayWebApiInSwagger: ${dashboard__displayWebApiInSwagger:-false}
      dashboard__useAuth: ${dashboard__useAuth:-false}
      dashboard__dashboardLoginApi: ${dashboard__dashboardLoginApi:-/api/account/login}
      dashboard__externalLinks__0__title: ${dashboard__externalLinks__0__title:-swagger docs}
      dashboard__externalLinks__0__path: ${dashboard__externalLinks__0__path:-http://localhost}
      dashboard__externalLinks__0__icon: ${dashboard__externalLinks__0__icon:-iconfont icon-swagger}
      dashboard__externalLinks__1__title: ${dashboard__externalLinks__1__title:-SkyWalking}
      dashboard__externalLinks__1__path: ${dashboard__externalLinks__1__path:-http://localhost:8180}
      dashboard__externalLinks__2__title: ${dashboard__externalLinks__2__title:-Github}
      dashboard__externalLinks__2__path: ${dashboard__externalLinks__2__path:-https://github.com/liuhll/silky}
      dashboard__externalLinks__2__icon: ${dashboard__externalLinks__2__icon:-iconfont icon-github} 
      dashboard__externalLinks__3__title: ${dashboard__externalLinks__3__title:-Gitee}
      dashboard__externalLinks__3__path: ${dashboard__externalLinks__3__path:-https://gitee.com/liuhll2/silky}
      dashboard__externalLinks__3__icon: ${dashboard__externalLinks__3__icon:-iconfont icon-gitee2}
      dashboard__externalLinks__4__title: ${dashboard__externalLinks__4__title:-healthchecks-ui}
      dashboard__externalLinks__4__path: ${dashboard__externalLinks__4__path:-http://localhost/healthchecks-ui}
      healthChecksUI__healthChecks__0__name: ${healthChecksUI__healthChecks__silkyrpc__name:-silkyrpc}
      healthChecksUI__healthChecks__0__uri: ${healthChecksUI__healthChecks__silkyrpc__uri:-http://127.0.0.1/silkyrpc/healthz}
    ports:
      - 80:80
    networks: 
      - silky_service_net

networks:
  silky_service_net: 
    external:
      name: silky_service_net